### ISSUE TITLE
New icons to represent more Data/Jupyter cases

### ISSUE THREAD

**Issue by echarles** [datalayer/icons#13]
We need icons for the following cases (see below image)

- [ ] Notebook
- [ ] Cell
- [ ] Output
- [ ] IpWidgets
- [ ] Terminal
- [ ] Console
- [ ] Commands
- [ ] Dialog
- [ ] File Browser
- [ ] Dialog
- [ ] Settings

<img width="1184" alt="Screenshot 2023-05-08 at 11 39 51" src="https://user-images.githubusercontent.com/226720/236791641-e6a976f1-e0e9-4597-ae81-65ffe7b9a55f.png">

**Comment by im-adithya** [comment]
Can't we reuse icons from https://primer.style/design/foundations/icons?
There seems to be an overlap for most, let me know if there are any that don't fit and need a custom icon

## Notebook
<img width="607" alt="Screenshot 2023-05-09 at 10 04 43 PM" src="https://github.com/datalayer/icons/assets/64399555/f87a5c90-5671-4ced-985f-0772762d7657">

 Cell - https://primer.style/design/foundations/icons/diamond-16
 Output - https://primer.style/design/foundations/icons/sign-out-16
 IpWidgets - https://primer.style/design/foundations/icons/apps-16 / https://primer.style/design/foundations/icons/rows-16
 Terminal - https://primer.style/design/foundations/icons/terminal-16
 Console - ?
 Commands - https://primer.style/design/foundations/icons/command-palette-16
 Dialog - https://primer.style/design/foundations/icons/code-review-16
 File Browser - https://primer.style/design/foundations/icons/file-directory-16
 Lumino - ?
 Settings - https://primer.style/design/foundations/icons/gear-16

**Comment by echarles** [comment]
We should indeed reuse as much as we can, but reexport when suited under the adhoc name, eg @datalayer-icons/.../Cell. would reexport https://primer.style/design/foundations/icons/diamond-16

I still think most of the current ocitcons icons do not represent well the intent (a Diamond is not a Jupyter Cell at all).

**Comment by im-adithya** [comment]
Yes, I was thinking if we can do something like:

`import { DiamondIcon as JupyterCellIcon } from "../react/outline";`

But I'm fine with re-exporting them from here, please let me know what icons fit best and what don't (not sure about the Jupyter Icons)

**Comment by echarles** [comment]
Your proposals for Terminal, Commands, Dialog, File Browser, Settings sound good.
Let's catchup for the others.

**Comment by im-adithya** [comment]
Updated the above comment ✅
